#!/usr/bin/env bash
set -euo pipefail

MYSQL_HOST=${MYSQL_HOST:-mysql}
MYSQL_PORT=${MYSQL_PORT:-3306}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-devcontainer}
MYSQL_USERNAME=${MYSQL_USERNAME:-rails}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-rails}
MYSQL_DEVELOPMENT_DB=${MYSQL_DEVELOPMENT_DB:-activerecord_tenanted_development}
MYSQL_TEST_DB=${MYSQL_TEST_DB:-activerecord_tenanted_test}

SQL=$(cat <<SQL
CREATE DATABASE IF NOT EXISTS \`${MYSQL_DEVELOPMENT_DB}\`;
CREATE DATABASE IF NOT EXISTS \`${MYSQL_TEST_DB}\`;
CREATE USER IF NOT EXISTS '${MYSQL_USERNAME}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${MYSQL_DEVELOPMENT_DB}\`.* TO '${MYSQL_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON \`${MYSQL_TEST_DB}\`.* TO '${MYSQL_USERNAME}'@'%';
FLUSH PRIVILEGES;
SQL
)

MYSQL_PWD="${MYSQL_ROOT_PASSWORD}" mysql \
  --protocol=tcp \
  -h "${MYSQL_HOST}" \
  -P "${MYSQL_PORT}" \
  -u root \
  --skip-ssl \
  --execute "${SQL}"

echo "[devcontainer] MySQL schemas '${MYSQL_DEVELOPMENT_DB}' and '${MYSQL_TEST_DB}' are ready."
